apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  namespace: kafka
spec:
  type: NodePort
  ports:
    - name: kafka
      port: 9092
      protocol: TCP
      nodePort: 30092
      targetPort: kafka-port
    - name: zookeeper
      port: 2181
      protocol: TCP
      nodePort: 32181
      targetPort: zookeeper-port
  selector:
    ess: kafka-app