apiVersion: v1
kind: Service
metadata:
  namespace: mysql
  name: mysql-svc
spec:
  type: LoadBalancer
  ports:
    - port: 3306
      protocol: TCP
      targetPort: mysql-port
  selector:
    db: mysql-app