apiVersion: v1
kind: Service
metadata:
  namespace: mysql
  name: mysql-svc
spec:
  type: NodePort
  ports:
    - port: 3306
      protocol: TCP
      nodePort: 30306
      targetPort: mysql-port
  selector:
    db: mysql-app