apiVersion: v1
kind: Service
metadata:
  name: pg-svc
  namespace: postgresql
spec:
  type: NodePort
  ports:
    - port: 5432
      protocol: TCP
      nodePort: 30432
      targetPort: pg-port
  selector:
    db: pg-app